// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: ESP32_240240LCD_TRY

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_ContainerTop;
extern lv_obj_t * ui_CITY;
extern lv_obj_t * ui_ContainerMiddleLeft;
extern lv_obj_t * ui_BIGHH;
extern lv_obj_t * ui_colon;
extern lv_obj_t * ui_BIGMM;
extern lv_obj_t * ui_BIGDATE;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

