// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: ESP32_240240LCD_TRY

#include "ui.h"

lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_ContainerTop = NULL;
lv_obj_t * ui_CITY = NULL;
lv_obj_t * ui_ContainerMiddleLeft = NULL;
lv_obj_t * ui_BIGHH = NULL;
lv_obj_t * ui_colon = NULL;
lv_obj_t * ui_BIGMM = NULL;
lv_obj_t * ui_BIGDATE = NULL;
lv_obj_t * ui_Spinner1 = NULL;
// event funtions

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerTop = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_ContainerTop);
    lv_obj_set_width(ui_ContainerTop, 230);
    lv_obj_set_height(ui_ContainerTop, 50);
    lv_obj_set_x(ui_ContainerTop, 0);
    lv_obj_set_y(ui_ContainerTop, -90);
    lv_obj_set_align(ui_ContainerTop, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContainerTop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CITY = lv_label_create(ui_ContainerTop);
    lv_obj_set_width(ui_CITY, 142);
    lv_obj_set_height(ui_CITY, 18);
    lv_obj_set_x(ui_CITY, -42);
    lv_obj_set_y(ui_CITY, -16);
    lv_obj_set_align(ui_CITY, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_CITY, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_CITY, "Godakawela");
    lv_obj_set_style_text_color(ui_CITY, lv_color_hex(0x0EB12B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CITY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CITY, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CITY, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerMiddleLeft = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_ContainerMiddleLeft);
    lv_obj_set_width(ui_ContainerMiddleLeft, 177);
    lv_obj_set_height(ui_ContainerMiddleLeft, 76);
    lv_obj_set_x(ui_ContainerMiddleLeft, -24);
    lv_obj_set_y(ui_ContainerMiddleLeft, -18);
    lv_obj_set_align(ui_ContainerMiddleLeft, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContainerMiddleLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_ContainerMiddleLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_ContainerMiddleLeft, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerMiddleLeft, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerMiddleLeft, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_BIGHH = lv_label_create(ui_ContainerMiddleLeft);
    lv_obj_set_width(ui_BIGHH, 66);
    lv_obj_set_height(ui_BIGHH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BIGHH, -50);
    lv_obj_set_y(ui_BIGHH, -15);
    lv_obj_set_align(ui_BIGHH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BIGHH, "00");
    lv_obj_set_style_text_align(ui_BIGHH, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BIGHH, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_colon = lv_label_create(ui_ContainerMiddleLeft);
    lv_obj_set_width(ui_colon, 12);
    lv_obj_set_height(ui_colon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_colon, -1);
    lv_obj_set_y(ui_colon, -17);
    lv_obj_set_align(ui_colon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_colon, ":");
    lv_obj_set_style_text_align(ui_colon, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_colon, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BIGMM = lv_label_create(ui_ContainerMiddleLeft);
    lv_obj_set_width(ui_BIGMM, 66);
    lv_obj_set_height(ui_BIGMM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BIGMM, 48);
    lv_obj_set_y(ui_BIGMM, -15);
    lv_obj_set_align(ui_BIGMM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BIGMM, "00");
    lv_obj_set_style_text_color(ui_BIGMM, lv_color_hex(0xFD5C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BIGMM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BIGMM, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BIGMM, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BIGDATE = lv_label_create(ui_ContainerMiddleLeft);
    lv_obj_set_width(ui_BIGDATE, 162);
    lv_obj_set_height(ui_BIGDATE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BIGDATE, -6);
    lv_obj_set_y(ui_BIGDATE, 23);
    lv_obj_set_align(ui_BIGDATE, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_BIGDATE, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_BIGDATE, "2025 - 2 -25 Sun");

    ui_Spinner1 = lv_spinner_create(ui_Home);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_x(ui_Spinner1, 65);
    lv_obj_set_y(ui_Spinner1, 64);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    ui_Home = NULL;
    ui_ContainerTop = NULL;
    ui_CITY = NULL;
    ui_ContainerMiddleLeft = NULL;
    ui_BIGHH = NULL;
    ui_colon = NULL;
    ui_BIGMM = NULL;
    ui_BIGDATE = NULL;
    ui_Spinner1 = NULL;

}
